name: Deploy Telegram Bot to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies into package/
        run: |
          mkdir -p package
          pip install -r requirements.txt -t package

      - name: Copy bot code into package/
        run: cp ToEnWikipediaBot.py package/

      - name: Zip application
        run: |
          cd package
          zip -r ../package.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region:            ${{ secrets.AWS_REGION }}
          function_name:         ${{ secrets.LAMBDA_FUNCTION_NAME }}
          zip_file:              package.zip
